### ISSUE TITLE
write a manifest to deploy the app

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/chatgpt-plugin#5]
this is an example of a manifest:

```
packages:
  address:
    inputs:
       githubtoken: ${GITHUB_TOKEN}
    actions:
      select:
        function:  address/Select.java
        web: true
        inputs:
          postgres: "jdbc:postgresql://yyy.nuvolaris.io/address?user=ubuntu&password=xxxx"

```

store your token as an enviromnet variable

write a manifest.yml and deploy the action with `wsk project deploy`

The application should work when you invoke it:

```
curl <action-url>?organization=apache
```
